dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

install:
  - sudo apt-get update
  - sudo apt-get install valgrind
  - sudo apt-get install libstdc++6
  - sudo apt-get install cmake

script:
  - cmake .
  - make
  #    - cmake --build .
  #    - ctest .
  - valgrind --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no