dist:     trusty    # используем Ubuntu 14.04 Trusty Tahr (а не 12.02 Precise Pangolin)
sudo:     required  # используем Virtual Machine (а не Docker container)

language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

env:
  # список переменных окружения, влияющих на матрицу сборки:
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
  - TARGET_CPU=x86 BUILD_CONFIGURATION=Release


install:
  # скрипт настройки среды и установки зависимостей:
  - source ci/travis/install-$TRAVIS_OS_NAME.sh

script:
  - cmake .
  - cmake --build .
  - ctest .