dist:     xenial
sudo:     required

language: c

os: linux

compiler: gcc

env:
  global:
  - CODECOV_TOKEN="2507d0ca-a1ef-498b-97ff-c5379b251a23"

install:
  - sudo apt-get update
  - sudo apt-get install cppcheck
  - sudo apt-get install valgrind
  - sudo apt-get install clang-format
  - sudo apt-get install lcov
  - sudo apt-get install libstdc++6
  - sudo apt-get install cmake
  # Google tests
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo cp *.a /usr/lib
  - cd -

before_script:

  - clang-format -i -style=Google *.h *.c
  - ./linters/run.sh || travis_terminate 1

script:

  - cmake .
  - make || travis_terminate 1
  - valgrind --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./a.out < in.txt || travis_terminate 1
  - valgrind --tool=memcheck --gen-suppressions=all --leak-check=full --leak-resolution=med --track-origins=yes --vgdb=no ./tester.out || travis_terminate 1

after_script:

  - lcov —capture —directory ./CMakeFiles/task_library.dir/project/src —output-file coverage.info
  - bash <(curl -s https://codecov.io/bash)
  - make clean